### ISSUE TITLE
[FEATURE] Add icons to callout render

### ISSUE THREAD

**Issue by Darginec05** [yoopta-editor/Yoopta-Editor#416]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Add icons to callout render

### Proposed Solution

Add icons to callout render

### Do you want to work on this issue?

Yes

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change adds icons to the callout render based on the callout theme. The icons are imported from the existing SVG files and displayed alongside the callout content.

You can review changes in this commit: https://github.com/mark-addams001881/yoopta-editor-Yoopta-Editor-416/commit/2228b15b85a3bae95bad7d4a4354745d5df35c26.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Darginec05** [comment]
added in v4.9.3
